name: 'Update Github Issue State'
description: 'Modify the state of a github issue'
inputs:
  github_token:
    description: 'The github token'
    required: true
  pull_number:
    description: 'The pull request number being modified'
    required: true
  state:
    description: 'The issue state to be set'
    required: true
    default: 'open'
runs:
  using: 'node20'
  main: 'index.js'