name: Testing

on:
    pull_request:
      types:
        - edited
        - opened
        - re-opened
        - closed

jobs:
    run_action:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Generate token
              id: generate-token
              uses: actions/create-github-app-token@v1
              with:
                app-id: '859026'
                private-key: ${{ secrets.APP_PEM }}
                owner: ${{ github.repository_owner }}
            - name: Testing
              uses: TheRecruitLab/issue-bot@feature/10/create-pr-when-branch-not-in-sync
              uses: ./actions/create-pr-if-out-of-sync
              with:
                  github_token: ${{ steps.generate-token.outputs.token }}
                  to: 'main'
                  from: 'feature/10/create-pr-when-branch-not-in-sync'